### ISSUE TITLE
Due to a bug in vng-api-common, nested serialization goes wrong if it fails.

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/vng-api-common#9] opened 2019-03-19 13:59 UTC
> Anna mentioned due to a bug in vng-api-common, nested serialization goes wrong if it fails.

We choose to be pragmatic and keep it as is, but would be nice if vng-api-common was updated :D

_Originally posted by @joeribekker in https://github.com/VNG-Realisatie/gemma-notificatiecomponent/pull/1/review_comment/create_

**Comment by sergei-maertens** [comment] 2019-05-13 08:23
@annashamray can you clarify what the issue is here?

**Comment by annashamray** [comment] 2019-05-14 08:20
In NRC component validation of `filter_groups` was placed in `AbonnementSerializer.validate` instead of `FilterGroupSerializer.validate`  - [code](https://github.com/VNG-Realisatie/gemma-notificatiecomponent/blob/fe162bd5d11d5524736b25d6bfffb34aae49b75d/src/notifications/api/serializers.py#L95)
It was made because if you place validate method into nested serializer (`FilterGroupSerializer` in this case) `get_validation_errors` from vng_api_common could not process this nested validation errors.

**Comment by sergei-maertens** [comment] 2019-06-28 09:16
Should be fixed by eb70ddd3266be146491582c8985548cedebb53ef

**Closed by sergei-maertens** 2019-06-28 09:16 UTC
